# Generated by Django 5.0.3 on 2024-03-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cagid', models.AutoField(primary_key=True, serialize=False)),
                ('cagname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cusid', models.AutoField(primary_key=True, serialize=False)),
                ('cusname', models.CharField(max_length=255)),
                ('cusphone', models.IntegerField(null=True)),
                ('cusnote', models.TextField(null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
