# Generated by Django 5.0.3 on 2024-03-21 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessSQL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=255)),
                ('itemprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itemnote', models.TextField()),
                ('cag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessSQL.category')),
            ],
        ),
    ]
