# Generated by Django 5.0.3 on 2024-03-21 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessSQL', '0002_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
    ]
