# Generated by Django 5.0.3 on 2024-04-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessSQL', '0004_detail_order_alter_item_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('topid', models.AutoField(primary_key=True, serialize=False)),
                ('topname', models.CharField(max_length=255, verbose_name='Topping')),
                ('topprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
            ],
            options={
                'db_table': 'topping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detail_Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
