# Generated by Django 5.0.4 on 2024-04-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessSQL', '0005_topping_detail_topping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail_topping',
            options={'managed': False},
        ),
    ]
