# Generated by Django 5.0.4 on 2024-04-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessSQL', '0006_alter_detail_topping_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail_topping',
            table='detail_topping',
        ),
    ]
